#Testing actions workflow with a Greeting when user pushes to main branch
name: Greeting on Push 

on: 
  push: 
    branches: [main] 

jobs:
  greet-user: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repo 
        uses: actions/checkout@v3

      - name: Print Greeting 
        run: echo "Hi there! Thank you for pushing to the main repository"
